
services:
  backend_rds:
    build: ./backend_rds
    container_name: backend_rds
    ports:
      - "8000:8000"
    volumes:
      - ./backend_rds:/app
    env_file:
    - .env
    depends_on:
      - db
  

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
    - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    
  backend_redis:
    image: backend_redis_image
    container_name: backend_redis
    ports:
      - "8001:8001"
    restart: always
    env_file:
    - .env
    depends_on:
     - redis

  redis:
    image: redis:7
    container_name: redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
    ports:
      - "6379:6379"
    restart: always
volumes:
  pg_data: