name: CI/CD to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push backend-rds
      run: |
        cd backend_rds
        docker build -t backend-rds .
        docker tag backend-rds:latest 881490118484.dkr.ecr.eu-central-1.amazonaws.com/backend-rds:latest
        docker push 881490118484.dkr.ecr.eu-central-1.amazonaws.com/backend-rds:latest
        cd ..

    - name: Build and push backend-redis
      run: |
        cd backend_redis
        docker build -t backend-redis .
        docker tag backend-redis:latest 881490118484.dkr.ecr.eu-central-1.amazonaws.com/backend-redis:latest
        docker push 881490118484.dkr.ecr.eu-central-1.amazonaws.com/backend-redis:latest